api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    formats:
        jsonld: ['application/ld+json']  
        html: [text/html]
        multipart: ['multipart/form-data'] 
        json: ['application/json']   
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
